version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - middleware
    networks:
      - app-network

  middleware:
    build: ./middleware
    ports:
      - "3001:3001"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=image_manager
    depends_on:
      - mysql
      - storage-node-1
      - storage-node-2
      - storage-node-3
    volumes:
      - ./middleware/src/config:/app/src/config
      - ./middleware/uploads:/app/uploads
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: image_manager
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - app-network

  storage-node-1:
    build: ./storage-node
    ports:
      - "3002:3002"
    environment:
      - NODE_ID=1
      - MAX_STORAGE=104857600  # 100MB en bytes
    volumes:
      - ./storage-node-1-data:/app/src/storage
    networks:
      - app-network

  storage-node-2:
    build: ./storage-node
    ports:
      - "3003:3002"
    environment:
      - NODE_ID=2
      - MAX_STORAGE=104857600  # 100MB en bytes
    volumes:
      - ./storage-node-2-data:/app/src/storage
    networks:
      - app-network

  storage-node-3:
    build: ./storage-node
    ports:
      - "3004:3002"
    environment:
      - NODE_ID=3
      - MAX_STORAGE=104857600  # 100MB en bytes
    volumes:
      - ./storage-node-3-data:/app/src/storage
    networks:
      - app-network

  # storage-node-4:
  #   build: ./storage-node
  #   ports:
  #     - "3005:3002"
  #   environment:
  #     - NODE_ID=4
  #     - MAX_STORAGE=104857600  # 100MB en bytes
  #   volumes:
  #     - ./storage-node-4-data:/app/src/storage
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: